query ParseQuery($feed: String!) {
  podcast(feed: $feed) {
    title
    crc
    author
    description
    subtitle
    artwork
    episodes {
      id
      url
      published
      title
      shownotes
      duration
    }
  }
}
