service: parser

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  timeout: 20
  region: eu-west-1
  apiGateway:
    shouldStartNameWithService: true
  environment:
    stage: ${self:provider.stage}

functions:
  graph:
    handler: src/handler.graph
    events:
      - http:
          path: /
          method: get
      - http:
          path: /
          method: post

  parser:
    handler: src/handler.parse
    events:
      - http:
          path: /parse
          method: post

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 9000
    lambdaPort: 3003
    noPrependStageInUrl: true
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
    includeModules: true
