service: parser

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'prod'}
  region: eu-west-1
  apiGateway:
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - ${ssm:/echo/ddb/podcasts/arn}
        - ${ssm:/echo/ddb/episodes/arn}
        - ${ssm:/echo/ddb/locks/arn}
        - ${ssm:/echo/ddb/websub/arn}
    - Effect: 'Allow'
      Action:
        - 'sns:Publish'
      Resource:
        - ${ssm:/echo/sns/resize/arn}
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
        - 'arn:aws:lambda:*'
  environment:
    stage: ${self:provider.stage}
    PI_API_KEY: ${ssm:/echo/pi/key}
    PI_API_SECRET: ${ssm:/echo/pi/secret~true}
    RESIZE_SNS: ${ssm:/echo/sns/resize/arn}
    PARSER_AUTH: ${ssm:/parser/auth~true}

functions:
  graph:
    handler: src/gql/handler.server
    events:
      - http:
          path: /graphql
          method: get
      - http:
          path: /graphql
          method: post

  parsePodcast:
    handler: src/parser/api.parsePodcast
    memorySize: 512
    timeout: 30
    events:
      - sns:
          arn: ${ssm:/echo/sns/parser/arn}

  httpWrap:
    handler: src/parser/api.httpWrap
    events:
      - http:
          path: /parse
          method: post

  websubDB:
    handler: src/websub/handler.dbUpdate
    events:
      - stream:
          type: dynamodb
          arn: ${ssm:/echo/ddb/websub/streamarn}

  websubPush:
    handler: src/websub/handler.pushHandler
    events:
      - http:
          path: /{any+}
          method: get
      - http:
          path: /{any+}
          method: post

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 9000
    lambdaPort: 3003
    noPrependStageInUrl: true
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
    includeModules:
      forceExclude:
        - aws-sdk
