query ParseQuery($feed: String!) {
  podcast(feed: $feed) {
    title
    crc
    author
    description
    subtitle
    artwork
    generator
    nextPage
    lastPage
    hub
    self
    episodes {
      id
      url
      published
      title
      shownotes
      duration
    }
  }
}
