type Podcast {
  title: String
  author: String
  description: String
  artwork: String
  episodes(limit: Int): [Episode!]!
  crc: ID
  index: String
  generator: ID
  nextPage: String
  lastPage: String
  hub: String
  self: String
}
